### ISSUE TITLE
Stacktrace on interpreter crash

### ISSUE THREAD

**Issue by vvergu** [metaborg/dynsem#73]
Try to produce a stack trace of reduction rules when the interpreter crashes. This should make debugging bad semantics **way** easier.

**Comment by vvergu** [comment]
0f0aee1 implements functionality for obtaining a stacktrace in the specification domain. Here's an example of a trace caused by attempting to write a `null` semantic component at a rule application premise:

```
Exception in thread "main" org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionFailure: Attempted to write null component at index 1
Frame: App1_2_Term -default->
     e_1=Lit_1(42)
     E_1={"iszero" ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})}
     v_2=null
     F_2=null
     v_1=NumV_1(42)
     F_1=Ok_0()
     H_2=null
     H_1={}
     v_3=ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})
     H_3={}
Frame: App_2_Term -default->
     e_1=Var_1(iszero)
     E_1={"iszero" ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})}
     v_2=null
     F_2=null
     v_1=ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})
     F_1=Ok_0()
     e_2=Lit_1(42)
     H_2=null
     H_1={}
     H_3={}
Frame: Catch_2_Term -default->
     e_1=App_2(Var_1(iszero), Lit_1(42))
     E_1={"iszero" ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})}
     v_2=null
     F_2=null
     v_1=null
     F_1=null
     e_2=Lit_1(123)
     H_2=null
     H_1=null
     H_3={}
Frame: Let2_2_Term -default->
     e_1=Catch_2(App_2(Var_1(iszero), Lit_1(42)), Lit_1(123))
     E_1={"iszero" ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})}
     v_1=null
     F_1=null
     H_2={}
     H_1=null
Frame: Let1_3_Term -default->
     E_1={"iszero" ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})}
     e_1=Catch_2(App_2(Var_1(iszero), Lit_1(42)), Lit_1(123))
     v_2=ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})
     F_2=null
     E_2={}
     F_1=Ok_0()
     v_1=null
     H_2=null
     H_1={}
     x15=iszero
     H_3={}
Frame: Let_3_Term -default->
     e_1=Fun_2(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))))
     E_1={}
     v_2=null
     F_2=null
     v_1=ClosV_3(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999))), {})
     F_1=Ok_0()
     e_2=Catch_2(App_2(Var_1(iszero), Lit_1(42)), Lit_1(123))
     x14=iszero
     H_2=null
     H_1={}
     H_3={}
Frame: Program_1_Term -init->
     e_1=Let_3(iszero, Fun_2(a, Ifz_3(Var_1(a), Lit_1(1), Plus_2(Raise_0(), Lit_1(999)))), Catch_2(App_2(Var_1(iszero), Lit_1(42)), Lit_1(123)))
     v_1=null
Frame: TemporaryRoot@b59d31
    at org.metaborg.meta.lang.dynsem.interpreter.utils.InterpreterUtils.setComponent(InterpreterUtils.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.RelationPremiseInputBuilder.executeObjectArray(RelationPremiseInputBuilder.java:56)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.InvokeRelationNode.execute(InvokeRelationNode.java:22)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:38)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.executeMainRules(RuleUnionNode.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.execute(RuleUnionNode.java:32)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionRoot.execute(RuleUnionRoot.java:28)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNode.doDirect(DispatchNode.java:34)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$DirectNode_.executeRuleResult(DispatchNodeGen.java:157)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$BaseNode_.acceptAndExecute(DispatchNodeGen.java:75)
    at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:407)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$UninitializedNode_.executeRuleResult(DispatchNodeGen.java:115)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen.execute(DispatchNodeGen.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.InvokeRelationNode.execute(InvokeRelationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:38)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.executeMainRules(RuleUnionNode.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.execute(RuleUnionNode.java:32)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionRoot.execute(RuleUnionRoot.java:28)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNode.doDirect(DispatchNode.java:34)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$DirectNode_.executeRuleResult(DispatchNodeGen.java:157)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$BaseNode_.acceptAndExecute(DispatchNodeGen.java:75)
    at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:407)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$UninitializedNode_.executeRuleResult(DispatchNodeGen.java:115)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen.execute(DispatchNodeGen.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.InvokeRelationNode.execute(InvokeRelationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:38)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.executeMainRules(RuleUnionNode.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.execute(RuleUnionNode.java:32)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionRoot.execute(RuleUnionRoot.java:28)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNode.doDirect(DispatchNode.java:34)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$DirectNode_.executeRuleResult(DispatchNodeGen.java:157)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$BaseNode_.acceptAndExecute(DispatchNodeGen.java:75)
    at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:407)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$UninitializedNode_.executeRuleResult(DispatchNodeGen.java:115)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen.execute(DispatchNodeGen.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.InvokeRelationNode.execute(InvokeRelationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:38)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.executeMainRules(RuleUnionNode.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.execute(RuleUnionNode.java:32)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionRoot.execute(RuleUnionRoot.java:28)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNode.doDirect(DispatchNode.java:34)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$DirectNode_.executeRuleResult(DispatchNodeGen.java:157)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$BaseNode_.acceptAndExecute(DispatchNodeGen.java:75)
    at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:407)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$UninitializedNode_.executeRuleResult(DispatchNodeGen.java:115)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen.execute(DispatchNodeGen.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.InvokeRelationNode.execute(InvokeRelationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:38)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.executeMainRules(RuleUnionNode.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.execute(RuleUnionNode.java:32)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionRoot.execute(RuleUnionRoot.java:28)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNode.doDirect(DispatchNode.java:34)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$DirectNode_.executeRuleResult(DispatchNodeGen.java:157)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$BaseNode_.acceptAndExecute(DispatchNodeGen.java:75)
    at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:407)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$UninitializedNode_.executeRuleResult(DispatchNodeGen.java:115)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen.execute(DispatchNodeGen.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.InvokeRelationNode.execute(InvokeRelationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:38)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.executeMainRules(RuleUnionNode.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.execute(RuleUnionNode.java:32)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionRoot.execute(RuleUnionRoot.java:28)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNode.doDirect(DispatchNode.java:34)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$DirectNode_.executeRuleResult(DispatchNodeGen.java:157)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$BaseNode_.acceptAndExecute(DispatchNodeGen.java:75)
    at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:407)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$UninitializedNode_.executeRuleResult(DispatchNodeGen.java:115)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen.execute(DispatchNodeGen.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.InvokeRelationNode.execute(InvokeRelationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:38)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.executeMainRules(RuleUnionNode.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.execute(RuleUnionNode.java:32)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionRoot.execute(RuleUnionRoot.java:28)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNode.doDirect(DispatchNode.java:34)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$DirectNode_.executeRuleResult(DispatchNodeGen.java:157)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$BaseNode_.acceptAndExecute(DispatchNodeGen.java:75)
    at com.oracle.truffle.api.dsl.internal.SpecializationNode.uninitialized(SpecializationNode.java:407)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen$UninitializedNode_.executeRuleResult(DispatchNodeGen.java:115)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.DispatchNodeGen.execute(DispatchNodeGen.java:36)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.reduction.InvokeRelationNode.execute(InvokeRelationNode.java:23)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.premises.RelationPremise.execute(RelationPremise.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.evaluatePremises(ReductionRule.java:48)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.ReductionRule.execute(ReductionRule.java:38)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.executeMainRules(RuleUnionNode.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionNode.execute(RuleUnionNode.java:32)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleUnionRoot.execute(RuleUnionRoot.java:28)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at org.metaborg.meta.lang.dynsem.interpreter.DynSemRuleForeignAccess$DynSemForeignCallerRootNode.execute(DynSemRuleForeignAccess.java:52)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:69)
    at com.oracle.truffle.api.interop.CachedObjectAccessNode.doAccess(CachedObjectAccessNode.java:55)
    at com.oracle.truffle.api.interop.CachedObjectAccessNode.executeWith(CachedObjectAccessNode.java:50)
    at com.oracle.truffle.api.interop.UnresolvedObjectAccessNode.executeWith(UnresolvedObjectAccessNode.java:45)
    at com.oracle.truffle.api.interop.ForeignObjectAccessHeadNode.executeForeignImpl(ForeignObjectAccessHeadNode.java:59)
    at com.oracle.truffle.api.interop.ForeignAccess.send(ForeignAccess.java:119)
    at com.oracle.truffle.api.vm.SymbolInvokerImpl$TemporaryRoot.execute(SymbolInvokerImpl.java:87)
    at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:84)
    at com.oracle.truffle.api.vm.PolyglotEngine$Value$2.compute(PolyglotEngine.java:737)
    at com.oracle.truffle.api.vm.ComputeInExecutor.run(ComputeInExecutor.java:93)
    at com.oracle.truffle.api.vm.ComputeInExecutor.perform(ComputeInExecutor.java:83)
    at com.oracle.truffle.api.vm.PolyglotEngine$Value.execute(PolyglotEngine.java:745)
    at org.metaborg.meta.lang.dynsem.interpreter.DynSemEntryPoint$1.call(DynSemEntryPoint.java:58)
    at org.metaborg.meta.lang.dynsem.interpreter.DynSemEntryPoint$1.call(DynSemEntryPoint.java:1)
    at org.metaborg.simpl.interpreter.generated.simplEntryPoint.evaluate(simplEntryPoint.java:47)
    at org.metaborg.simpl.interpreter.generated.simplEntryPoint.main(simplEntryPoint.java:41)
```
