### ISSUE TITLE
Interpreter crashes with NotImplementedException on rule with nested list

### ISSUE THREAD

**Issue by milosonator** [metaborg/dynsem#84]
Having a rule like this:

```
  wrap-values([v|vs]) --> [ wv | wvs ] : List(List(CodeSequence))
    where
      [Wrapped(v)] => wv;
      wrap-values(vs) --> wvs.
```

Will prevent the interpreter from running, it will crash and present this error:

```
Exception in thread "main" org.spoofax.terms.util.NotImplementedException: Unsupported term build: List([Con("Wrapped",[VarRef("v1")])])
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.building.TermBuild.create(TermBuild.java:125)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.building.ListBuild.create(ListBuild.java:43)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.building.TermBuild.create(TermBuild.java:111)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleTarget.create(RuleTarget.java:45)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.Rule.create(Rule.java:98)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.Rule.create(Rule.java:64)
    at org.metaborg.meta.lang.dynsem.interpreter.nodes.rules.RuleRegistry.populate(RuleRegistry.java:89)
    at org.metaborg.grace.interpreter.generated.graceLanguage.parse(graceLanguage.java:31)
    at com.oracle.truffle.api.TruffleLanguage$AccessAPI.eval(TruffleLanguage.java:511)
    at com.oracle.truffle.api.impl.Accessor.eval(Accessor.java:158)
    at com.oracle.truffle.api.vm.PolyglotEngine$SPIAccessor.eval(PolyglotEngine.java:954)
    at com.oracle.truffle.api.vm.PolyglotEngine.evalImpl(PolyglotEngine.java:457)
    at com.oracle.truffle.api.vm.PolyglotEngine.access$200(PolyglotEngine.java:103)
    at com.oracle.truffle.api.vm.PolyglotEngine$2.compute(PolyglotEngine.java:441)
    at com.oracle.truffle.api.vm.ComputeInExecutor.run(ComputeInExecutor.java:93)
    at com.oracle.truffle.api.vm.ComputeInExecutor.perform(ComputeInExecutor.java:83)
    at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:444)
    at com.oracle.truffle.api.vm.PolyglotEngine.eval(PolyglotEngine.java:398)
    at org.metaborg.meta.lang.dynsem.interpreter.DynSemEntryPoint.getCallable(DynSemEntryPoint.java:53)
    at org.metaborg.meta.lang.dynsem.interpreter.DynSemEntryPoint.getCallable(DynSemEntryPoint.java:41)
    at org.metaborg.grace.interpreter.generated.graceEntryPoint.evaluate(graceEntryPoint.java:47)
    at org.metaborg.grace.interpreter.generated.graceEntryPoint.main(graceEntryPoint.java:41)
```

**Comment by vvergu** [comment]
Yes, this is indeed a bug. I think you can work around the issue by replacing the premise `[Wrapped(s)] => wv;` with `[Wrapped(s)] : List(CodeSequence) => wv;`.

**Comment by milosonator** [comment]
The workaround unfortunately doesn't work. For more information, here is the rule from the core.ds:

```
  DS ds1, CS cs1 |- wrap-values([ v1 | vs1 ]) :: Map(Int,O) OH1, Map(Int,M) MH1 -default-> [ [ Wrapped(v1) | [  ] ] | wvs ] :: Map(Int,O) OH2, Map(Int,M) MH2
  where
    DS ds1, CS cs1 |- wrap-values(vs1) :: Map(Int,O) OH1, Map(Int,M) MH1 -default-> wvs :: Map(Int,O) OH2, Map(Int,M) MH2.
```
